apiVersion: v1
kind: Pod
metadata:
  name: sriovpodc
  namespace: sriov-testing
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
                "name": "sriov-net-enp5s0f1-netdev",
                "ips": ["192.168.10.12/24", "2001::12/64"]
        }
]'
spec:
  containers:
  - name: sample-container
    image: centos:8
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
