apiVersion: v1
kind: Pod
metadata:
  name: sriovpoda
  namespace: sriov-testing
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
	{
		"name": "sriov-net-enp5s0f0-vfiopci",
		"ips": ["192.168.10.10/24", "2001::10/64"]
	}
]'
spec:
  containers:
  - name: sample-container
    image: centos:8
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
